"""KJV psalm superscriptions + Pauline colophons (exact KJPBS wording).

Extracted from the SWORD KJV 2.6.1 OSIS module (the same source
purebiblesearch built its .ccdb databases from) and verified
word-for-word against bbl-kjv1769.ccdb verse-0 records (116 + 14).
Values keep <transChange> elements; bible.py renders those as
[...] and strips everything else for searching.

Regenerate: unzip the kjv20140215_sword_2p6.zip module to /tmp/kjvosis
and re-run the extractor (see shell history / README note).
"""
from __future__ import annotations

SUPERSCRIPTIONS: dict[tuple[str, int], str] = {
    ("Ps", 3): 'A Psalm of David, when he fled from Absalom his son.',
    ("Ps", 4): 'To the chief Musician on Neginoth, A Psalm of David.',
    ("Ps", 5): 'To the chief Musician upon Nehiloth, A Psalm of David.',
    ("Ps", 6): 'To the chief Musician on Neginoth upon Sheminith, A Psalm of David.',
    ("Ps", 7): 'Shiggaion of David, which he sang unto the Lord, concerning the words of Cush the Benjamite.',
    ("Ps", 8): 'To the chief Musician upon Gittith, A Psalm of David.',
    ("Ps", 9): 'To the chief Musician upon Muthlabben, A Psalm of David.',
    ("Ps", 11): 'To the chief Musician, <transChange type="added">A Psalm</transChange> of David.',
    ("Ps", 12): 'To the chief Musician upon Sheminith, A Psalm of David.',
    ("Ps", 13): 'To the chief Musician, A Psalm of David.',
    ("Ps", 14): 'To the chief Musician, <transChange type="added">A Psalm</transChange> of David.',
    ("Ps", 15): 'A Psalm of David.',
    ("Ps", 16): 'Michtam of David.',
    ("Ps", 17): 'A Prayer of David.',
    ("Ps", 18): 'To the chief Musician, <transChange type="added">A Psalm</transChange> of David, the servant of the Lord, who spake unto the Lord the words of this song in the day <transChange type="added">that</transChange> the Lord delivered him from the hand of all his enemies, and from the hand of Saul: And he said,',
    ("Ps", 19): 'To the chief Musician, A Psalm of David.',
    ("Ps", 20): 'To the chief Musician, A Psalm of David.',
    ("Ps", 21): 'To the chief Musician, A Psalm of David.',
    ("Ps", 22): 'To the chief Musician upon Aijeleth Shahar, A Psalm of David.',
    ("Ps", 23): 'A Psalm of David.',
    ("Ps", 24): 'A Psalm of David.',
    ("Ps", 25): '<transChange type="added">A Psalm</transChange> of David.',
    ("Ps", 26): '<transChange type="added">A Psalm</transChange> of David.',
    ("Ps", 27): '<transChange type="added">A Psalm</transChange> of David.',
    ("Ps", 28): '<transChange type="added">A Psalm</transChange> of David.',
    ("Ps", 29): 'A Psalm of David.',
    ("Ps", 30): 'A Psalm <transChange type="added">and</transChange> Song <transChange type="added">at</transChange> the dedication of the house of David.',
    ("Ps", 31): 'To the chief Musician, A Psalm of David.',
    ("Ps", 32): '<transChange type="added">A Psalm</transChange> of David, Maschil.',
    ("Ps", 34): '<transChange type="added">A Psalm</transChange> of David, when he changed his behaviour before Abimelech; who drove him away, and he departed.',
    ("Ps", 35): '<transChange type="added">A Psalm</transChange> of David.',
    ("Ps", 36): 'To the chief Musician, <transChange type="added">A Psalm</transChange> of David the servant of the Lord.',
    ("Ps", 37): '<transChange type="added">A Psalm</transChange> of David.',
    ("Ps", 38): 'A Psalm of David, to bring to remembrance.',
    ("Ps", 39): 'To the chief Musician, <transChange type="added">even</transChange> to Jeduthun, A Psalm of David.',
    ("Ps", 40): 'To the chief Musician, A Psalm of David.',
    ("Ps", 41): 'To the chief Musician, A Psalm of David.',
    ("Ps", 42): 'To the chief Musician, Maschil, for the sons of Korah.',
    ("Ps", 44): 'To the chief Musician for the sons of Korah, Maschil.',
    ("Ps", 45): 'To the chief Musician upon Shoshannim, for the sons of Korah, Maschil, A Song of loves.',
    ("Ps", 46): 'To the chief Musician for the sons of Korah, A Song upon Alamoth.',
    ("Ps", 47): 'To the chief Musician, A Psalm for the sons of Korah.',
    ("Ps", 48): 'A Song <transChange type="added">and</transChange> Psalm for the sons of Korah.',
    ("Ps", 49): 'To the chief Musician, A Psalm for the sons of Korah.',
    ("Ps", 50): 'A Psalm of Asaph.',
    ("Ps", 51): 'To the chief Musician, A Psalm of David, when Nathan the prophet came unto him, after he had gone in to Bath–sheba.',
    ("Ps", 52): 'To the chief Musician, Maschil, <transChange type="added">A Psalm</transChange> of David, when Doeg the Edomite came and told Saul, and said unto him, David is come to the house of Ahimelech.',
    ("Ps", 53): 'To the chief Musician upon Mahalath, Maschil, <transChange type="added">A Psalm</transChange> of David.',
    ("Ps", 54): 'To the chief Musician on Neginoth, Maschil, <transChange type="added">A Psalm</transChange> of David, when the Ziphims came and said to Saul, Doth not David hide himself with us?',
    ("Ps", 55): 'To the chief Musician on Neginoth, Maschil, <transChange type="added">A Psalm</transChange> of David.',
    ("Ps", 56): 'To the chief Musician upon Jonath–elem–rechokim, Michtam of David, when the Philistines took him in Gath.',
    ("Ps", 57): 'To the chief Musician, Al–taschith, Michtam of David, when he fled from Saul in the cave.',
    ("Ps", 58): 'To the chief Musician, Al–taschith, Michtam of David.',
    ("Ps", 59): 'To the chief Musician, Al–taschith, Michtam of David; when Saul sent, and they watched the house to kill him.',
    ("Ps", 60): 'To the chief Musician upon Shushan–eduth, Michtam of David, to teach; when he strove with Aram–naharaim and with Aram–zobah, when Joab returned, and smote of Edom in the valley of salt twelve thousand.',
    ("Ps", 61): 'To the chief Musician upon Neginah, <transChange type="added">A Psalm</transChange> of David.',
    ("Ps", 62): 'To the chief Musician, to Jeduthun, A Psalm of David.',
    ("Ps", 63): 'A Psalm of David, when he was in the wilderness of Judah.',
    ("Ps", 64): 'To the chief Musician, A Psalm of David.',
    ("Ps", 65): 'To the chief Musician, A Psalm <transChange type="added">and</transChange> Song of David.',
    ("Ps", 66): 'To the chief Musician, A Song <transChange type="added">or</transChange> Psalm.',
    ("Ps", 67): 'To the chief Musician on Neginoth, A Psalm <transChange type="added">or</transChange> Song.',
    ("Ps", 68): 'To the chief Musician, A Psalm <transChange type="added">or</transChange> Song of David.',
    ("Ps", 69): 'To the chief Musician upon Shoshannim, <transChange type="added">A Psalm</transChange> of David.',
    ("Ps", 70): 'To the chief Musician, <transChange type="added">A Psalm</transChange> of David, to bring to remembrance.',
    ("Ps", 72): '<transChange type="added">A Psalm</transChange> for Solomon.',
    ("Ps", 73): 'A Psalm of Asaph.',
    ("Ps", 74): 'Maschil of Asaph.',
    ("Ps", 75): 'To the chief Musician, Al–taschith, A Psalm <transChange type="added">or</transChange> Song of Asaph.',
    ("Ps", 76): 'To the chief Musician on Neginoth, A Psalm <transChange type="added">or</transChange> Song of Asaph.',
    ("Ps", 77): 'To the chief Musician, to Jeduthun, A Psalm of Asaph.',
    ("Ps", 78): 'Maschil of Asaph.',
    ("Ps", 79): 'A Psalm of Asaph.',
    ("Ps", 80): 'To the chief Musician upon Shoshannim–eduth, A Psalm of Asaph.',
    ("Ps", 81): 'To the chief Musician upon Gittith, <transChange type="added">A Psalm</transChange> of Asaph.',
    ("Ps", 82): 'A Psalm of Asaph.',
    ("Ps", 83): 'A Song <transChange type="added">or</transChange> Psalm of Asaph.',
    ("Ps", 84): 'To the chief Musician upon Gittith, A Psalm for the sons of Korah.',
    ("Ps", 85): 'To the chief Musician, A Psalm for the sons of Korah.',
    ("Ps", 86): 'A Prayer of David.',
    ("Ps", 87): 'A Psalm <transChange type="added">or</transChange> Song for the sons of Korah.',
    ("Ps", 88): 'A Song <transChange type="added">or</transChange> Psalm for the sons of Korah, to the chief Musician upon Mahalath Leannoth, Maschil of Heman the Ezrahite.',
    ("Ps", 89): 'Maschil of Ethan the Ezrahite.',
    ("Ps", 90): 'A Prayer of Moses the man of God.',
    ("Ps", 92): 'A Psalm <transChange type="added">or</transChange> Song for the sabbath day.',
    ("Ps", 98): 'A Psalm.',
    ("Ps", 100): 'A Psalm of praise.',
    ("Ps", 101): 'A Psalm of David.',
    ("Ps", 102): 'A Prayer of the afflicted, when he is overwhelmed, and poureth out his complaint before the Lord.',
    ("Ps", 103): '<transChange type="added">A Psalm</transChange> of David.',
    ("Ps", 108): 'A Song <transChange type="added">or</transChange> Psalm of David.',
    ("Ps", 109): 'To the chief Musician, A Psalm of David.',
    ("Ps", 110): 'A Psalm of David.',
    ("Ps", 120): 'A Song of degrees.',
    ("Ps", 121): 'A Song of degrees.',
    ("Ps", 122): 'A Song of degrees of David.',
    ("Ps", 123): 'A Song of degrees.',
    ("Ps", 124): 'A Song of degrees of David.',
    ("Ps", 125): 'A Song of degrees.',
    ("Ps", 126): 'A Song of degrees.',
    ("Ps", 127): 'A Song of degrees for Solomon.',
    ("Ps", 128): 'A Song of degrees.',
    ("Ps", 129): 'A Song of degrees.',
    ("Ps", 130): 'A Song of degrees.',
    ("Ps", 131): 'A Song of degrees of David.',
    ("Ps", 132): 'A Song of degrees.',
    ("Ps", 133): 'A Song of degrees of David.',
    ("Ps", 134): 'A Song of degrees.',
    ("Ps", 138): '<transChange type="added">A Psalm</transChange> of David.',
    ("Ps", 139): 'To the chief Musician, A Psalm of David.',
    ("Ps", 140): 'To the chief Musician, A Psalm of David.',
    ("Ps", 141): 'A Psalm of David.',
    ("Ps", 142): 'Maschil of David; A Prayer when he was in the cave.',
    ("Ps", 143): 'A Psalm of David.',
    ("Ps", 144): '<transChange type="added">A Psalm</transChange> of David.',
    ("Ps", 145): 'David’s <transChange type="added">Psalm</transChange> of praise.',
}

COLOPHONS: dict[str, str] = {
    'Rom': 'Written to the Romans from Corinthus, <transChange type="added">and sent</transChange> by Phebe servant of the church at Cenchrea.',
    '1Cor': 'The first <transChange type="added">epistle</transChange> to the Corinthians was written from Philippi by Stephanas, and Fortunatus, and Achaicus, and Timotheus.',
    '2Cor': 'The second <transChange type="added">epistle</transChange> to the Corinthians was written from Philippi, <transChange type="added">a city</transChange> of Macedonia, by Titus and Lucas.',
    'Gal': 'Unto the Galatians written from Rome.',
    'Eph': 'Written from Rome unto the Ephesians by Tychicus.',
    'Phil': 'It was written to the Philippians from Rome by Epaphroditus.',
    'Col': 'Written from Rome to the Colossians by Tychicus and Onesimus.',
    '1Thess': 'The first <transChange type="added">epistle</transChange> unto the Thessalonians was written from Athens.',
    '2Thess': 'The second <transChange type="added">epistle</transChange> to the Thessalonians was written from Athens.',
    '1Tim': 'The first to Timothy was written from Laodicea, which is the chiefest city of Phrygia Pacatiana.',
    '2Tim': 'The second <transChange type="added">epistle</transChange> unto Timotheus, ordained the first bishop of the church of the Ephesians, was written from Rome, when Paul was brought before Nero the second time.',
    'Titus': 'It was written to Titus, ordained the first bishop of the church of the Cretians, from Nicopolis of Macedonia.',
    'Phlm': 'Written from Rome to Philemon, by Onesimus a servant.',
    'Heb': 'Written to the Hebrews from Italy by Timothy.',
}
